/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'role' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'category' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalStockValue' : IDL.Float64,
  'pendingSalesCount' : IDL.Nat,
  'totalSalesRevenue' : IDL.Float64,
  'lowStockProducts' : IDL.Vec(Product),
});
export const PurchaseOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'supplierName' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(OrderItem),
  'supplierId' : IDL.Nat,
});
export const SalesOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'customerId' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SessionToken = IDL.Record({
  'token' : IDL.Text,
  'username' : IDL.Text,
  'role' : IDL.Text,
});
export const StaffAccount = IDL.Record({
  'name' : IDL.Text,
  'username' : IDL.Text,
});
export const CustomerAccount = IDL.Record({
  'name' : IDL.Text,
  'username' : IDL.Text,
});
export const PackingMaster = IDL.Record({
  'id' : IDL.Nat,
  'packingName' : IDL.Text,
  'itemName' : IDL.Text,
  'packingType' : IDL.Text,
  'standardWeight' : IDL.Float64,
  'tareWeight' : IDL.Float64,
  'marka' : IDL.Text,
  'size' : IDL.Text,
  'unitType' : IDL.Text,
  'isReturnable' : IDL.Bool,
  'crateCategory' : IDL.Text,
  'crateCode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createPurchaseOrder' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'createSalesOrder' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'createSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteSupplier' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getPurchaseOrder' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(PurchaseOrder)],
      ['query'],
    ),
  'getSalesOrder' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(SalesOrder)],
      ['query'],
    ),
  'getSupplier' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Supplier)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPurchaseOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PurchaseOrder)],
      ['query'],
    ),
  'listSalesOrders' : IDL.Func([IDL.Text], [IDL.Vec(SalesOrder)], ['query']),
  'listSuppliers' : IDL.Func([IDL.Text], [IDL.Vec(Supplier)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(SessionToken)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
  'updatePurchaseOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateSalesOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'removeStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'listStaff' : IDL.Func([IDL.Text], [IDL.Vec(StaffAccount)], ['query']),
  'addCustomerLogin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'removeCustomerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'listCustomerLogins' : IDL.Func([IDL.Text], [IDL.Vec(CustomerAccount)], ['query']),
  'createPacking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'listPackings' : IDL.Func([IDL.Text], [IDL.Vec(PackingMaster)], ['query']),
  'getPacking' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(PackingMaster)], ['query']),
  'deletePacking' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'category' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalStockValue' : IDL.Float64,
    'pendingSalesCount' : IDL.Nat,
    'totalSalesRevenue' : IDL.Float64,
    'lowStockProducts' : IDL.Vec(Product),
  });
  const PurchaseOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'supplierName' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(OrderItem),
    'supplierId' : IDL.Nat,
  });
  const SalesOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'customerId' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SessionToken = IDL.Record({
    'token' : IDL.Text,
    'username' : IDL.Text,
    'role' : IDL.Text,
  });
  const StaffAccount = IDL.Record({
    'name' : IDL.Text,
    'username' : IDL.Text,
  });
  const CustomerAccount = IDL.Record({
    'name' : IDL.Text,
    'username' : IDL.Text,
  });
  const PackingMaster = IDL.Record({
    'id' : IDL.Nat,
    'packingName' : IDL.Text,
    'itemName' : IDL.Text,
    'packingType' : IDL.Text,
    'standardWeight' : IDL.Float64,
    'tareWeight' : IDL.Float64,
    'marka' : IDL.Text,
    'size' : IDL.Text,
    'unitType' : IDL.Text,
    'isReturnable' : IDL.Bool,
    'crateCategory' : IDL.Text,
    'crateCode' : IDL.Text,
  });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createPurchaseOrder' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'createSalesOrder' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'createSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteSupplier' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(Customer)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getPurchaseOrder' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(PurchaseOrder)],
        ['query'],
      ),
    'getSalesOrder' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(SalesOrder)],
        ['query'],
      ),
    'getSupplier' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(Supplier)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPurchaseOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PurchaseOrder)],
        ['query'],
      ),
    'listSalesOrders' : IDL.Func([IDL.Text], [IDL.Vec(SalesOrder)], ['query']),
    'listSuppliers' : IDL.Func([IDL.Text], [IDL.Vec(Supplier)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(SessionToken)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
    'updatePurchaseOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSalesOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'removeStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'listStaff' : IDL.Func([IDL.Text], [IDL.Vec(StaffAccount)], ['query']),
    'addCustomerLogin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'removeCustomerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'listCustomerLogins' : IDL.Func([IDL.Text], [IDL.Vec(CustomerAccount)], ['query']),
    'createPacking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'listPackings' : IDL.Func([IDL.Text], [IDL.Vec(PackingMaster)], ['query']),
    'getPacking' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(PackingMaster)], ['query']),
    'deletePacking' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };